name: CD Pipeline

on: 
  
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [completed]
    branches: ['main']

jobs:
  docker:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    permissions:
      contents: read
      packages: write

    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      # -----------
      # Login to GitHub Container Registry
      # -----------
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # -----------
      # Generate metadata for Docker image
      # Tags the image with the commit SHA and 'latest' if on the main branch
      # -----------
      - name: Extract Docker metadata
        id: metadata 
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,prefix=sha-,suffix=,enable={{is_default_branch}}
            type=raw,value=latest,enable={{is_default_branch}}
      
      # -----------
      # Configurate Docker Buildex
      # Extend Docker Buildx with QEMU for multi-platform builds
      # -----------
      - name: Set up Dokcer Buildex
        uses: docker/setup-buildx-action@v3
      
      # -----------
      # Build and push Docker image
      # -----------
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
